# Generated by Django 5.1.6 on 2025-03-01 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteanonimo',
            name='direccion',
        ),
        migrations.AddField(
            model_name='clienteanonimo',
            name='apellido',
            field=models.CharField(default='invitado', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='Dirección Desconocida', max_length=200),
        ),
        migrations.AlterField(
            model_name='clienteanonimo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_anonimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.clienteanonimo'),
        ),
    ]
