# Generated by Django 5.1.6 on 2025-03-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_clienteanonimo_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago')], default='efectivo', max_length=20),
        ),
    ]
